### ISSUE TITLE
Public Method: Add Object

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/isodom.js#4]
Public method that allows you to add an object to the grid.

Once executed a preview of the object should be shown with 50% opacity. When the player clicks on a cell the object will be added to the grid.

If the player clicks `Right Mouse Button` or press `R` a rotate event will happen rotating the object 90 degrees. In Developer Tycoon these are called orientation 1-4. 

A public method for cancelling the operation should be added to. Pressing `ESC` while in preview-mode should also cancel the operation.

**Comment by InDieTasten** [comment]
Not 100% sure that placement and previewing placement itself of things is within the scope of isodom.js.
Why not have an API that easily lets you place items. The current selection of an item, it's orientation and visuals(opacity, image itself, etc. ) are very specific features, that feel quite narrow in my opinion.

But I'm still not 100% of the scope of isodom.js.

**Comment by Nathix** [comment]
isodom.js would only provide the API to make adding/removing/moving possible - this is more of an example we could make to show what is possible.

By default I am unsure if any functions would be added to events because we shouldn't hardcode them - e.g. someone may want to have an edit button that allows them to drag it around instead.

**Comment by InDieTasten** [comment]
yeah, that feels a lot better. the previewing etc. can be things built on top of that functionality then.

So a thing for the demo ui
